---
title: "techs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
#techs <- read_excel("~/Downloads/techs.xlsx", 
#    sheet = "Sheet2")
library(readxl)
library(rlang)
library(ggplot2)
library(dplyr)
library(psych)
library(nlme)
library(table1)
library(readxl)
library(tidyr)

#techs <- read_excel("TECHS_DATA_2024-03-21_1340.xlsx")
#View(techs)
#techs <- TECHS_16PrePost

```

#TECHS
```{r}
techs$age <- as.numeric(techs$age)
techs$days_since_injury_calc <- as.numeric(techs$days_since_injury_calc)
techs$sex_factor <- as.factor(techs$sex)
techs$annual_income_factor <- as.factor(techs$annual_income)
techs$ethnicity_factor <- as.factor(techs$ethnicity)
techs$race_factor <- as.factor(techs$race)
techs$randomization_group_factor <- as.factor(techs$randomization_group)

mean(techs$age)
sd(techs$age)
range(techs$age)
techs <- techs %>%
  mutate(randomization_group_factor = ifelse(randomization_group_factor == 0, "Aerobic", "Balance"))
techs <- techs %>%
  mutate(sex_factor = ifelse(sex_factor == 0, "Female", "Male"))
techs <- techs %>%
  mutate(ethnicity_factor = ifelse(ethnicity_factor == 0, "Hispanic or Latino", "NOT Hispanic or Latino"))
techs <- techs %>%
  mutate(race_factor = case_when(
    race == 0 ~ "American Indian/Alaska Native",
    race == 1 ~ "Asian",
    race == 2 ~ "Native Hawaiian/Pacific Islander",
    race == 3 ~ "Black or African American",
    race == 4 ~ "White/Caucasian",
    race == 5 ~ "Mixed Race",
    TRUE ~ as.character(race_factor)
  ))

techs <- techs %>%
  mutate(annual_income_factor = case_when(
    annual_income == 0 ~ ">$20K",
    annual_income == 1 ~ "$20K-$40K",
    annual_income == 2 ~ "$40K-$60K",
    annual_income == 3 ~ "$60K-$80K",
    annual_income == 4 ~ "$80K-$100K",
    annual_income == 5 ~ "$100K-$120K",
    annual_income == 6 ~ "$120K-$140K",
    annual_income == 7 ~ "$140K-$160K",
    annual_income == 8 ~ "$160K-$180K"
  ))
balance_ids <- c("1", "2", "7", "8", "9", "17", "21", "22", "24", "28", "29")
aerobic_ids <- c("3", "4", "10", "11", "12", "15", "19", "25", "26", "27")
dropout_ids <- c("5", "6", "13", "14", "16", "18", "20", "23", "30", "31", "32")
techs$intervention_group <- ifelse(techs$name %in% balance_ids, "balance",
                                   ifelse(techs$name %in% aerobic_ids, "aerobic",
                                   ifelse(techs$name %in% dropout_ids, "dropout", "ongoing")))
techs$Group <- ifelse(techs$name %in% balance_ids, "balance",
               ifelse(techs$name %in% aerobic_ids, "aerobic",
               ifelse(techs$name %in% dropout_ids, NA, NA)))


table1(~ factor(sex_factor) + age + factor(annual_income_factor) + days_since_injury + ethnicity_factor + factor(race_factor) + years_of_ed | factor(intervention_group), data=techs)



print(techs$referral_source)
ggplot(techs, aes(x = age)) +
  geom_histogram()
ggplot(techs, aes(x = sex)) +
  geom_histogram()

techs %>%
  ggplot(techs, aes(x=days_since_injury_calc)) +
    geom_histogram( binwidth=3, fill="#69b3a2", color="#e9ecef", alpha=0.9) +
    ggtitle("age") +
    theme_ipsum() +
    theme(
      plot.title = element_text(size=15)
    )

techs$ethnicity <- as.character(techs$ethnicity)
techs$global06 <- techs$promis_physical_activities
techs %>%
  ggplot( aes(x=wkday_sitting_hours)) +
    geom_histogram(stat = "count", fill="#69b3a2", color="#e9ecef", alpha=0.9) +
    ggtitle("Time Sitting") +
    theme_ipsum() +
    theme(
      plot.title = element_text(size=15) + 
       geom_density(color = "#000000", fill = "#F85700", alpha = 0.6)
      )

techs$relativevo2 <- (techs$vo2max/techs$weight)*1000
techs$BESS <- rowSums(techs[ , c("dls_firm","sls_firm","ts_firm","dsl_foam","sls_foam","ts_foam")], na.rm=TRUE)
techs$BESS <- rowSums(techs[ , c("dls_firm","sls_firm","ts_firm","dsl_foam","sls_foam","ts_foam")], na.rm=TRUE)

techs$BESS_v2 <- rowSums(techs[ , c("dls_firm_v2_821d7b","sls_firm_v2_835e98","ts_firm_v2_884cca","dsl_foam_v2_1082a5","sls_foam_v2_b7661f","ts_foam_v2_1424c9")], na.rm=TRUE)
```


#intervention
```{r}

techs$baseline_hr <- rowMeans(techs[, c("baseline_hr_int1_d5","baseline_hr_int1_d5_d2","baseline_hr_int1_d5_d3","baseline_hr_int1_d5_d4","baseline_hr_int1_d5_d5","baseline_hr_int1_d5_d6","baseline_hr_int1_d5_d7","baseline_hr_int1_d5_d8","baseline_hr_int1_d5_d9","baseline_hr_int1_d5_d10","baseline_hr_int1_d5_d11","baseline_hr_int1_d5_d12","baseline_hr_int1_d5_d13","baseline_hr_int1_d5_d14","baseline_hr_int1_d5_d15","baseline_hr_int1_d5_d16","baseline_hr_int1_d5_d17","baseline_hr_int1_d5_d18","baseline_hr_int1_d5_d19","baseline_hr_int1_d5_d20","baseline_hr_int1_d5_d21","baseline_hr_int1_d5_d22","baseline_hr_int1_d5_d23","baseline_hr_int1_d5_d24","baseline_hr_int1_d5_d25","baseline_hr_int1_d5_d26","baseline_hr_int1_d5_d27","baseline_hr_int1_d5_d28","baseline_hr_int1_d5_d29","baseline_hr_int1_d5_d30","baseline_hr_int1_d5_d31","baseline_hr_int1_d5_d32","baseline_hr_int1_d5_d33","baseline_hr_int1_d5_d34","baseline_hr_int1_d5_d35","baseline_hr_int1_d5_d36")], na.rm=TRUE)


techs$baseline_hr_perc <- rowMeans(techs[ , c("hr_max_baseline_int1_d5","hr_max_baseline_int1_d5_d2","hr_max_baseline_int1_d5_d3","hr_max_baseline_int1_d5_d4","hr_max_baseline_int1_d5_d5","hr_max_baseline_int1_d5_d6","hr_max_baseline_int1_d5_d7","hr_max_baseline_int1_d5_d8","hr_max_baseline_int1_d5_d9","hr_max_baseline_int1_d5_d10","hr_max_baseline_int1_d5_d11","hr_max_baseline_int1_d5_d12","hr_max_baseline_int1_d5_d13","hr_max_baseline_int1_d5_d14","hr_max_baseline_int1_d5_d15","hr_max_baseline_int1_d5_d16","hr_max_baseline_int1_d5_d17","hr_max_baseline_int1_d5_d18","hr_max_baseline_int1_d5_d19","hr_max_baseline_int1_d5_d20","hr_max_baseline_int1_d5_d21","hr_max_baseline_int1_d5_d22","hr_max_baseline_int1_d5_d23","hr_max_baseline_int1_d5_d24","hr_max_baseline_int1_d5_d25","hr_max_baseline_int1_d5_d26","hr_max_baseline_int1_d5_d27","hr_max_baseline_int1_d5_d28","hr_max_baseline_int1_d5_d29","hr_max_baseline_int1_d5_d30","hr_max_baseline_int1_d5_d31","hr_max_baseline_int1_d5_d32","hr_max_baseline_int1_d5_d33","hr_max_baseline_int1_d5_d34","hr_max_baseline_int1_d5_d35","hr_max_baseline_int1_d5_d36")], na.rm=TRUE)

techs$min05_hr <- rowMeans(techs[, c("hr_1_int1_d5","hr_1_int1_d5_d2","hr_1_int1_d5_d3","hr_1_int1_d5_d4","hr_1_int1_d5_d5","hr_1_int1_d5_d6","hr_1_int1_d5_d7","hr_1_int1_d5_d8","hr_1_int1_d5_d9","hr_1_int1_d5_d10","hr_1_int1_d5_d11","hr_1_int1_d5_d12","hr_1_int1_d5_d13","hr_1_int1_d5_d14","hr_1_int1_d5_d15","hr_1_int1_d5_d16","hr_1_int1_d5_d17","hr_1_int1_d5_d18","hr_1_int1_d5_d19","hr_1_int1_d5_d20","hr_1_int1_d5_d21","hr_1_int1_d5_d22","hr_1_int1_d5_d23","hr_1_int1_d5_d24","hr_1_int1_d5_d25","hr_1_int1_d5_d26","hr_1_int1_d5_d27","hr_1_int1_d5_d28","hr_1_int1_d5_d29","hr_1_int1_d5_d30","hr_1_int1_d5_d31","hr_1_int1_d5_d32","hr_1_int1_d5_d33","hr_1_int1_d5_d34","hr_1_int1_d5_d35","hr_1_int1_d5_d36")], na.rm=TRUE)
techs$min05_hr_perc <- rowMeans(techs[ , c("hr_max_1_int1_d5","hr_max_1_int1_d5_d2","hr_max_1_int1_d5_d3","hr_max_1_int1_d5_d4","hr_max_1_int1_d5_d5","hr_max_1_int1_d5_d6","hr_max_1_int1_d5_d7","hr_max_1_int1_d5_d8","hr_max_1_int1_d5_d9","hr_max_1_int1_d5_d10","hr_max_1_int1_d5_d11","hr_max_1_int1_d5_d12","hr_max_1_int1_d5_d13","hr_max_1_int1_d5_d14","hr_max_1_int1_d5_d15","hr_max_1_int1_d5_d16","hr_max_1_int1_d5_d17","hr_max_1_int1_d5_d18","hr_max_1_int1_d5_d19","hr_max_1_int1_d5_d20","hr_max_1_int1_d5_d21","hr_max_1_int1_d5_d22","hr_max_1_int1_d5_d23","hr_max_1_int1_d5_d24","hr_max_1_int1_d5_d25","hr_max_1_int1_d5_d26","hr_max_1_int1_d5_d27","hr_max_1_int1_d5_d28","hr_max_1_int1_d5_d29","hr_max_1_int1_d5_d30","hr_max_1_int1_d5_d31","hr_max_1_int1_d5_d32","hr_max_1_int1_d5_d33","hr_max_1_int1_d5_d34","hr_max_1_int1_d5_d35","hr_max_1_int1_d5_d36")], na.rm=TRUE)

techs$min10_hr <- rowMeans(techs[, c("hr_2_int1_d5","hr_2_int1_d5_d2","hr_2_int1_d5_d3","hr_2_int1_d5_d4","hr_2_int1_d5_d5","hr_2_int1_d5_d6","hr_2_int1_d5_d7","hr_2_int1_d5_d8","hr_2_int1_d5_d9","hr_2_int1_d5_d10","hr_2_int1_d5_d11","hr_2_int1_d5_d12","hr_2_int1_d5_d13","hr_2_int1_d5_d14","hr_2_int1_d5_d15","hr_2_int1_d5_d16","hr_2_int1_d5_d17","hr_2_int1_d5_d18","hr_2_int1_d5_d19","hr_2_int1_d5_d20","hr_2_int1_d5_d21","hr_2_int1_d5_d22","hr_2_int1_d5_d23","hr_2_int1_d5_d24","hr_2_int1_d5_d25","hr_2_int1_d5_d26","hr_2_int1_d5_d27","hr_2_int1_d5_d28","hr_2_int1_d5_d29","hr_2_int1_d5_d30","hr_2_int1_d5_d31","hr_2_int1_d5_d32","hr_2_int1_d5_d33","hr_2_int1_d5_d34","hr_2_int1_d5_d35","hr_2_int1_d5_d36")], na.rm=TRUE)
techs$min10_hr_perc <- rowMeans(techs[ , c("hr_max_2_int1_d5","hr_max_2_int1_d5_d2","hr_max_2_int1_d5_d3","hr_max_2_int1_d5_d4","hr_max_2_int1_d5_d5","hr_max_2_int1_d5_d6","hr_max_2_int1_d5_d7","hr_max_2_int1_d5_d8","hr_max_2_int1_d5_d9","hr_max_2_int1_d5_d10","hr_max_2_int1_d5_d11","hr_max_2_int1_d5_d12","hr_max_2_int1_d5_d13","hr_max_2_int1_d5_d14","hr_max_2_int1_d5_d15","hr_max_2_int1_d5_d16","hr_max_2_int1_d5_d17","hr_max_2_int1_d5_d18","hr_max_2_int1_d5_d19","hr_max_2_int1_d5_d20","hr_max_2_int1_d5_d21","hr_max_2_int1_d5_d22","hr_max_2_int1_d5_d23","hr_max_2_int1_d5_d24","hr_max_2_int1_d5_d25","hr_max_2_int1_d5_d26","hr_max_2_int1_d5_d27","hr_max_2_int1_d5_d28","hr_max_2_int1_d5_d29","hr_max_2_int1_d5_d30","hr_max_2_int1_d5_d31","hr_max_2_int1_d5_d32","hr_max_2_int1_d5_d33","hr_max_2_int1_d5_d34","hr_max_2_int1_d5_d35","hr_max_2_int1_d5_d36")], na.rm=TRUE)

techs$min15_hr <- rowMeans(techs[, c("hr_3_int1_d5","hr_3_int1_d5_d2","hr_3_int1_d5_d3","hr_3_int1_d5_d4","hr_3_int1_d5_d5","hr_3_int1_d5_d6","hr_3_int1_d5_d7","hr_3_int1_d5_d8","hr_3_int1_d5_d9","hr_3_int1_d5_d10","hr_3_int1_d5_d11","hr_3_int1_d5_d12","hr_3_int1_d5_d13","hr_3_int1_d5_d14","hr_3_int1_d5_d15","hr_3_int1_d5_d16","hr_3_int1_d5_d17","hr_3_int1_d5_d18","hr_3_int1_d5_d19","hr_3_int1_d5_d20","hr_3_int1_d5_d21","hr_3_int1_d5_d22","hr_3_int1_d5_d23","hr_3_int1_d5_d24","hr_3_int1_d5_d25","hr_3_int1_d5_d26","hr_3_int1_d5_d27","hr_3_int1_d5_d28","hr_3_int1_d5_d29","hr_3_int1_d5_d30","hr_3_int1_d5_d31","hr_3_int1_d5_d32","hr_3_int1_d5_d33","hr_3_int1_d5_d34","hr_3_int1_d5_d35","hr_3_int1_d5_d36")], na.rm=TRUE)
techs$min15_hr_perc <- rowMeans(techs[ , c("hr_max_3_int1_d5","hr_max_3_int1_d5_d2","hr_max_3_int1_d5_d3","hr_max_3_int1_d5_d4","hr_max_3_int1_d5_d5","hr_max_3_int1_d5_d6","hr_max_3_int1_d5_d7","hr_max_3_int1_d5_d8","hr_max_3_int1_d5_d9","hr_max_3_int1_d5_d10","hr_max_3_int1_d5_d11","hr_max_3_int1_d5_d12","hr_max_3_int1_d5_d13","hr_max_3_int1_d5_d14","hr_max_3_int1_d5_d15","hr_max_3_int1_d5_d16","hr_max_3_int1_d5_d17","hr_max_3_int1_d5_d18","hr_max_3_int1_d5_d19","hr_max_3_int1_d5_d20","hr_max_3_int1_d5_d21","hr_max_3_int1_d5_d22","hr_max_3_int1_d5_d23","hr_max_3_int1_d5_d24","hr_max_3_int1_d5_d25","hr_max_3_int1_d5_d26","hr_max_3_int1_d5_d27","hr_max_3_int1_d5_d28","hr_max_3_int1_d5_d29","hr_max_3_int1_d5_d30","hr_max_3_int1_d5_d31","hr_max_3_int1_d5_d32","hr_max_3_int1_d5_d33","hr_max_3_int1_d5_d34","hr_max_3_int1_d5_d35","hr_max_3_int1_d5_d36")], na.rm=TRUE)

techs$min20_hr <- rowMeans(techs[, c("hr_4_int1_d5","hr_4_int1_d5_d2","hr_4_int1_d5_d3","hr_4_int1_d5_d4","hr_4_int1_d5_d5","hr_4_int1_d5_d6","hr_4_int1_d5_d7","hr_4_int1_d5_d8","hr_4_int1_d5_d9","hr_4_int1_d5_d10","hr_4_int1_d5_d11","hr_4_int1_d5_d12","hr_4_int1_d5_d13","hr_4_int1_d5_d14","hr_4_int1_d5_d15","hr_4_int1_d5_d16","hr_4_int1_d5_d17","hr_4_int1_d5_d18","hr_4_int1_d5_d19","hr_4_int1_d5_d20","hr_4_int1_d5_d21","hr_4_int1_d5_d22","hr_4_int1_d5_d23","hr_4_int1_d5_d24","hr_4_int1_d5_d25","hr_4_int1_d5_d26","hr_4_int1_d5_d27","hr_4_int1_d5_d28","hr_4_int1_d5_d29","hr_4_int1_d5_d30","hr_4_int1_d5_d31","hr_4_int1_d5_d32","hr_4_int1_d5_d33","hr_4_int1_d5_d34","hr_4_int1_d5_d35","hr_4_int1_d5_d36")], na.rm=TRUE)
techs$min20_hr_perc <- rowMeans(techs[ , c("hr_max_4_int1_d5","hr_max_4_int1_d5_d2","hr_max_4_int1_d5_d3","hr_max_4_int1_d5_d4","hr_max_4_int1_d5_d5","hr_max_4_int1_d5_d6","hr_max_4_int1_d5_d7","hr_max_4_int1_d5_d8","hr_max_4_int1_d5_d9","hr_max_4_int1_d5_d10","hr_max_4_int1_d5_d11","hr_max_4_int1_d5_d12","hr_max_4_int1_d5_d13","hr_max_4_int1_d5_d14","hr_max_4_int1_d5_d15","hr_max_4_int1_d5_d16","hr_max_4_int1_d5_d17","hr_max_4_int1_d5_d18","hr_max_4_int1_d5_d19","hr_max_4_int1_d5_d20","hr_max_4_int1_d5_d21","hr_max_4_int1_d5_d22","hr_max_4_int1_d5_d23","hr_max_4_int1_d5_d24","hr_max_4_int1_d5_d25","hr_max_4_int1_d5_d26","hr_max_4_int1_d5_d27","hr_max_4_int1_d5_d28","hr_max_4_int1_d5_d29","hr_max_4_int1_d5_d30","hr_max_4_int1_d5_d31","hr_max_4_int1_d5_d32","hr_max_4_int1_d5_d33","hr_max_4_int1_d5_d34","hr_max_4_int1_d5_d35","hr_max_4_int1_d5_d36")], na.rm=TRUE)

techs$min25_hr <- rowMeans(techs[, c("hr_5_int1_d5","hr_5_int1_d5_d2","hr_5_int1_d5_d3","hr_5_int1_d5_d4","hr_5_int1_d5_d5","hr_5_int1_d5_d6","hr_5_int1_d5_d7","hr_5_int1_d5_d8","hr_5_int1_d5_d9","hr_5_int1_d5_d10","hr_5_int1_d5_d11","hr_5_int1_d5_d12","hr_5_int1_d5_d13","hr_5_int1_d5_d14","hr_5_int1_d5_d15","hr_5_int1_d5_d16","hr_5_int1_d5_d17","hr_5_int1_d5_d18","hr_5_int1_d5_d19","hr_5_int1_d5_d20","hr_5_int1_d5_d21","hr_5_int1_d5_d22","hr_5_int1_d5_d23","hr_5_int1_d5_d24","hr_5_int1_d5_d25","hr_5_int1_d5_d26","hr_5_int1_d5_d27","hr_5_int1_d5_d28","hr_5_int1_d5_d29","hr_5_int1_d5_d30","hr_5_int1_d5_d31","hr_5_int1_d5_d32","hr_5_int1_d5_d33","hr_5_int1_d5_d34","hr_5_int1_d5_d35","hr_5_int1_d5_d36")], na.rm=TRUE)
techs$min25_hr_perc <- rowMeans(techs[ , c("hr_max_5_int1_d5","hr_max_5_int1_d5_d2","hr_max_5_int1_d5_d3","hr_max_5_int1_d5_d4","hr_max_5_int1_d5_d5","hr_max_5_int1_d5_d6","hr_max_5_int1_d5_d7","hr_max_5_int1_d5_d8","hr_max_5_int1_d5_d9","hr_max_5_int1_d5_d10","hr_max_5_int1_d5_d11","hr_max_5_int1_d5_d12","hr_max_5_int1_d5_d13","hr_max_5_int1_d5_d14","hr_max_5_int1_d5_d15","hr_max_5_int1_d5_d16","hr_max_5_int1_d5_d17","hr_max_5_int1_d5_d18","hr_max_5_int1_d5_d19","hr_max_5_int1_d5_d20","hr_max_5_int1_d5_d21","hr_max_5_int1_d5_d22","hr_max_5_int1_d5_d23","hr_max_5_int1_d5_d24","hr_max_5_int1_d5_d25","hr_max_5_int1_d5_d26","hr_max_5_int1_d5_d27","hr_max_5_int1_d5_d28","hr_max_5_int1_d5_d29","hr_max_5_int1_d5_d30","hr_max_5_int1_d5_d31","hr_max_5_int1_d5_d32","hr_max_5_int1_d5_d33","hr_max_5_int1_d5_d34","hr_max_5_int1_d5_d35","hr_max_5_int1_d5_d36")], na.rm=TRUE)

techs$min30_hr <- rowMeans(techs[, c("hr_6_int1_d5","hr_6_int1_d5_d2","hr_6_int1_d5_d3","hr_6_int1_d5_d4","hr_6_int1_d5_d5","hr_6_int1_d5_d6","hr_6_int1_d5_d7","hr_6_int1_d5_d8","hr_6_int1_d5_d9","hr_6_int1_d5_d10","hr_6_int1_d5_d11","hr_6_int1_d5_d12","hr_6_int1_d5_d13","hr_6_int1_d5_d14","hr_6_int1_d5_d15","hr_6_int1_d5_d16","hr_6_int1_d5_d17","hr_6_int1_d5_d18","hr_6_int1_d5_d19","hr_6_int1_d5_d20","hr_6_int1_d5_d21","hr_6_int1_d5_d22","hr_6_int1_d5_d23","hr_6_int1_d5_d24","hr_6_int1_d5_d25","hr_6_int1_d5_d26","hr_6_int1_d5_d27","hr_6_int1_d5_d28","hr_6_int1_d5_d29","hr_6_int1_d5_d30","hr_6_int1_d5_d31","hr_6_int1_d5_d32","hr_6_int1_d5_d33","hr_6_int1_d5_d34","hr_6_int1_d5_d35","hr_6_int1_d5_d36")], na.rm=TRUE)
techs$min30_hr_perc <- rowMeans(techs[ , c("hr_max_6_int1_d5","hr_max_6_int1_d5_d2","hr_max_6_int1_d5_d3","hr_max_6_int1_d5_d4","hr_max_6_int1_d5_d5","hr_max_6_int1_d5_d6","hr_max_6_int1_d5_d7","hr_max_6_int1_d5_d8","hr_max_6_int1_d5_d9","hr_max_6_int1_d5_d10","hr_max_6_int1_d5_d11","hr_max_6_int1_d5_d12","hr_max_6_int1_d5_d13","hr_max_6_int1_d5_d14","hr_max_6_int1_d5_d15","hr_max_6_int1_d5_d16","hr_max_6_int1_d5_d17","hr_max_6_int1_d5_d18","hr_max_6_int1_d5_d19","hr_max_6_int1_d5_d20","hr_max_6_int1_d5_d21","hr_max_6_int1_d5_d22","hr_max_6_int1_d5_d23","hr_max_6_int1_d5_d24","hr_max_6_int1_d5_d25","hr_max_6_int1_d5_d26","hr_max_6_int1_d5_d27","hr_max_6_int1_d5_d28","hr_max_6_int1_d5_d29","hr_max_6_int1_d5_d30","hr_max_6_int1_d5_d31","hr_max_6_int1_d5_d32","hr_max_6_int1_d5_d33","hr_max_6_int1_d5_d34","hr_max_6_int1_d5_d35","hr_max_6_int1_d5_d36")], na.rm=TRUE)

#make long
long_techs <- techs %>%
  gather(key = "time_point", value = "heart_rate", baseline_hr, min05_hr, min10_hr, min15_hr, min20_hr, min25_hr, min30_hr)
#plot each participant
ggplot(long_techs, aes(x = time_point, y = heart_rate, group = name)) +
  geom_line() +
  geom_point() +
  facet_wrap(~ name, nrow = 3) +  # Assuming 12 participants, arrange them in 3 rows
  labs(x = "Time Point", y = "Heart Rate", title = "Heart Rate Over Time for Each Participant")
#plot all participants
long_techs <- techs %>%
  gather(key = "time_point", value = "heart_rate_perc", baseline_hr_perc, min05_hr_perc, min10_hr_perc, min15_hr_perc, min20_hr_perc, min25_hr_perc, min30_hr_perc)

ggplot(long_techs, aes(x = time_point, y = heart_rate_perc, group = name)) +
  geom_line() +
  geom_point() +
  facet_wrap(~ name, nrow = 3) +  # Assuming 12 participants, arrange them in 3 rows
  labs(x = "Time Point", y = "Heart Rate % ", title = "Heart Rate % Over Time for Each Participant")

ggplot(long_techs, aes(x = time_point, y = heart_rate_perc, color = factor(randomization_group))) +
    geom_line(aes(group = name), alpha = 0.5) +
    geom_smooth(method = "lm", se = FALSE, aes(group = randomization_group), size = 3) +  # Add trend lines
  scale_color_manual(values = c("#FBAE2D", "#052844"), 
                     name = "Randomization Group",
                     labels = c("0" = "Aerobic", "1" = "Balance")) +
  labs(x = "Time (Minutes)", y = "Heart Rate (% of max)", title = "HR Over Time for All Participants") +
  scale_x_discrete(labels = c("baseline_hr_perc" = "0", "min05_hr_perc" = "5", "min10_hr_perc" = "10", "min15_hr_perc" = "15", "min20_hr_perc" = "20", "min25_hr_perc" = "25", "min30_hr_perc" = "30")) +
  theme(panel.grid.major = element_blank(),    # Remove major gridlines
        panel.grid.minor = element_blank(),    # Remove minor gridlines
        panel.background = element_rect(fill = "white"),  # Set background to white
        axis.line = element_line(color = "black"),  # Specify axis line color
        axis.ticks = element_line(color = "black")) + 
    guides(color = guide_legend(title = "Randomization Group"))  # Set legend title

data_hr$group <- as.factor(data_hr$group)
data_hr$ID <- as.factor(data_hr$ID)
#plot HR line graphs
library(ggplot2)
#install.packages("reshape2")
library(reshape2)

data_long <- melt(data_hr, id.vars = "time")
ggplot(data_hr, aes(x = time, y = HR, color = ID)) +
  geom_line() +
  labs(title = "raw HR across intervention", x = "30 Minute session", y = "RAW HR")

ggplot(data_hr, aes(x = time, y = HR_perc, color = ID)) +
  geom_line() +
  theme_classic(base_size = 12) +
  geom_line(size = 2) + theme(legend.position = "none")  +
  labs(title = "", x = "30 Minute session", y = "% of HR max")

```

```{r}
techs$cif_1 <- rowMeans(techs[, c("baseline_cif_int1_d5","baseline_cif_int1_d5_d2","baseline_cif_int1_d5_d3","baseline_cif_int1_d5_d4","baseline_cif_int1_d5_d5","baseline_cif_int1_d5_d6","baseline_cif_int1_d5_d7","baseline_cif_int1_d5_d8","baseline_cif_int1_d5_d9","baseline_cif_int1_d5_d10","baseline_cif_int1_d5_d11","baseline_cif_int1_d5_d12","baseline_cif_int1_d5_d13","baseline_cif_int1_d5_d14","baseline_cif_int1_d5_d15","baseline_cif_int1_d5_d16","baseline_cif_int1_d5_d17","baseline_cif_int1_d5_d18","baseline_cif_int1_d5_d19","baseline_cif_int1_d5_d20","baseline_cif_int1_d5_d21","baseline_cif_int1_d5_d22","baseline_cif_int1_d5_d23","baseline_cif_int1_d5_d24","baseline_cif_int1_d5_d25","baseline_cif_int1_d5_d26","baseline_cif_int1_d5_d27","baseline_cif_int1_d5_d28","baseline_cif_int1_d5_d29","baseline_cif_int1_d5_d30","baseline_cif_int1_d5_d31","baseline_cif_int1_d5_d32","baseline_cif_int1_d5_d33","baseline_cif_int1_d5_d34","baseline_cif_int1_d5_d35","baseline_cif_int1_d5_d36")], na.rm=TRUE)

techs$cif_2 <- rowMeans(techs[, c("min5_cif_int1","min5_cif_int2","min5_cif_int3","min5_cif_int4","min5_cif_int5","min5_cif_int6","min5_cif_int7","min5_cif_int8","min5_cif_int9","min5_cif_int10","min5_cif_int11","min5_cif_int12","min5_cif_int13","min5_cif_int14","min5_cif_int15","min5_cif_int16","min5_cif_int17","min5_cif_int18","min5_cif_int19","min5_cif_int20","min5_cif_int21","min5_cif_int22","min5_cif_int23","min5_cif_int24","min5_cif_int25","min5_cif_int26","min5_cif_int27","min5_cif_int28","min5_cif_int29","min5_cif_int30","min5_cif_int31","min5_cif_int32","min5_cif_int33","min5_cif_int34","min5_cif_int35","min5_cif_int36")], na.rm=TRUE)

techs$cif_3 <- rowMeans(techs[, c("min10_cif_int1","min10_cif_int2","min10_cif_int3","min10_cif_int4","min10_cif_int5","min10_cif_int6","min10_cif_int7","min10_cif_int8","min10_cif_int9","min10_cif_int10","min10_cif_int11","min10_cif_int12","min10_cif_int13","min10_cif_int14","min10_cif_int15","min10_cif_int16","min10_cif_int17","min10_cif_int18","min10_cif_int19","min10_cif_int20","min10_cif_int21","min10_cif_int22","min10_cif_int23","min10_cif_int24","min10_cif_int25","min10_cif_int26","min10_cif_int27","min10_cif_int28","min10_cif_int29","min10_cif_int30","min10_cif_int31","min10_cif_int32","min10_cif_int33","min10_cif_int34","min10_cif_int35","min10_cif_int36")], na.rm=TRUE)

techs$cif_4 <- rowMeans(techs[, c("min15_cif_int1","min15_cif_int2","min15_cif_int3","min15_cif_int4","min15_cif_int5","min15_cif_int6","min15_cif_int7","min15_cif_int8","min15_cif_int9","min15_cif_int10","min15_cif_int11","min15_cif_int12","min15_cif_int13","min15_cif_int14","min15_cif_int15","min15_cif_int16","min15_cif_int17","min15_cif_int18","min15_cif_int19","min15_cif_int20","min15_cif_int21","min15_cif_int22","min15_cif_int23","min15_cif_int24","min15_cif_int25","min15_cif_int26","min15_cif_int27","min15_cif_int28","min15_cif_int29","min15_cif_int30","min15_cif_int31","min15_cif_int32","min15_cif_int33","min15_cif_int34","min15_cif_int35","min15_cif_int36")], na.rm=TRUE)

techs$cif_5 <- rowMeans(techs[, c("min20_cif_int1","min20_cif_int2","min20_cif_int3","min20_cif_int4","min20_cif_int5","min20_cif_int6","min20_cif_int7","min20_cif_int8","min20_cif_int9","min20_cif_int10","min20_cif_int11","min20_cif_int12","min20_cif_int13","min20_cif_int14","min20_cif_int15","min20_cif_int16","min20_cif_int17","min20_cif_int18","min20_cif_int19","min20_cif_int20","min20_cif_int21","min20_cif_int22","min20_cif_int23","min20_cif_int24","min20_cif_int25","min20_cif_int26","min20_cif_int27","min20_cif_int28","min20_cif_int29","min20_cif_int30","min20_cif_int31","min20_cif_int32","min20_cif_int33","min20_cif_int34","min20_cif_int35","min20_cif_int36")], na.rm=TRUE)

techs$cif_6 <- rowMeans(techs[, c("min25_cif_int1","min25_cif_int2","min25_cif_int3","min25_cif_int4","min25_cif_int5","min25_cif_int6","min25_cif_int7","min25_cif_int8","min25_cif_int9","min25_cif_int10","min25_cif_int11","min25_cif_int12","min25_cif_int13","min25_cif_int14","min25_cif_int15","min25_cif_int16","min25_cif_int17","min25_cif_int18","min25_cif_int19","min25_cif_int20","min25_cif_int21","min25_cif_int22","min25_cif_int23","min25_cif_int24","min25_cif_int25","min25_cif_int26","min25_cif_int27","min25_cif_int28","min25_cif_int29","min25_cif_int30","min25_cif_int31","min25_cif_int32","min25_cif_int33","min25_cif_int34","min25_cif_int35","min25_cif_int36")], na.rm=TRUE)

techs$cif_7 <- rowMeans(techs[, c("min30_cif_int1","min30_cif_int2","min30_cif_int3","min30_cif_int4","min30_cif_int5","min30_cif_int6","min30_cif_int7","min30_cif_int8","min30_cif_int9","min30_cif_int10","min30_cif_int11","min30_cif_int12","min30_cif_int13","min30_cif_int14","min30_cif_int15","min30_cif_int16","min30_cif_int17","min30_cif_int18","min30_cif_int19","min30_cif_int20","min30_cif_int21","min30_cif_int22","min30_cif_int23","min30_cif_int24","min30_cif_int25","min30_cif_int26","min30_cif_int27","min30_cif_int28","min30_cif_int29","min30_cif_int30","min30_cif_int31","min30_cif_int32","min30_cif_int33","min30_cif_int34","min30_cif_int35","min30_cif_int36")], na.rm=TRUE)


#make long
long_techs <- techs %>%
  gather(key = "time_point", value = "cif", cif_1, cif_2, cif_3, cif_4, cif_5, cif_6, cif_7)
#plot each participant
ggplot(long_techs, aes(x = time_point, y = cif, group = name)) +
  geom_line() +
  geom_point() +
  facet_wrap(~ name, nrow = 3) +  # Assuming 12 participants, arrange them in 3 rows
  labs(x = "Time Point", y = "CIF", title = "Symptom Score")

#plot all participants
long_techs$time_point1 <- factor(long_techs$time_point, labels = c("0", "5", "10", "15", "20", "25", "30"))

ggplot(long_techs, aes(x = time_point, y = cif, color = factor(randomization_group))) +
    geom_line(aes(group = name), alpha = 0.5) +
    geom_smooth(method = "lm", se = FALSE, aes(group = randomization_group), size = 3) +  # Add trend lines
  scale_color_manual(values = c("#FBAE2D", "#052844"), 
                     name = "Randomization Group",
                     labels = c("0" = "Aerobic", "1" = "Balance")) +
  labs(x = "Time (Minutes)", y = "Symptom Score", title = "Symptom Score Over Time for All Participants") +
  scale_x_discrete(labels = c("cif_1" = "0", "cif_2" = "5", "cif_3" = "10", "cif_4" = "15", "cif_5" = "20", "cif_6" = "25", "cif_7" = "30")) +
  theme(panel.grid.major = element_blank(),    # Remove major gridlines
        panel.grid.minor = element_blank(),    # Remove minor gridlines
        panel.background = element_rect(fill = "white"),  # Set background to white
        axis.line = element_line(color = "black"),  # Specify axis line color
        axis.ticks = element_line(color = "black")) + 
    guides(color = guide_legend(title = "Randomization Group"))  # Set legend title


long_techs$group <- as.factor(long_techs$group)
long_techs$ID <- as.factor(long_techs$ID)
#plot cif line graphs
library(ggplot2)
library(reshape2)

data_long <- melt(data_cif, id.vars = "time")
ggplot(data_cif, aes(x = time, y = cif, color = ID)) +
  geom_line() + 
  theme_bw() +
  theme_classic(base_size = 25) +
  geom_line(size = 2) +
  labs(title = "Symptoms across intervention", x = "30 Minute session", y = "Symptom Score") 

```


```{r pre/post data}
#plot differences in pre/post data

techs_long$timepoint <- as.factor(techs_long$timepoint)
techs_long$ID <- as.factor(techs_long$ID)


ggplot(techs_long, aes(x = timepoint, y = bess, group = ID, color = ID)) +
  geom_line() +
    theme_bw() +
  theme_classic(base_size = 25) +
    geom_line(size = 2) +
  labs(title = "Bess", x = "Timepoint", y = "Total # of Errors")
```


```{r pre/post data}
long_df_vf_a <- techs %>%
  select(name, Group, verbal_fluency_a, verbal_fluency_a_v2) %>%
  gather(key = "timepoint", value = "value", verbal_fluency_a, verbal_fluency_a_v2)
long_df_vf_a <- long_df_vf_a %>%
  mutate(timepoint = ifelse(timepoint == "verbal_fluency_a", "1", "2"))

ggplot(long_df_vf_a %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = as.factor(Group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "Verbal Fluency A", x = "Timepoint", y = "# of words")

long_df_vf_f <- techs %>%
  select(name, Group, verbal_fluency_f, verbal_fluency_f_v2) %>%
  gather(key = "timepoint", value = "value", verbal_fluency_f, verbal_fluency_f_v2)
long_df_vf_f <- long_df_vf_f %>%
  mutate(timepoint = ifelse(timepoint == "verbal_fluency_f", "1", "2"))
ggplot(long_df_vf_f %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = as.factor(Group))) +
  geom_line(linetype = "dashed") +
  theme_bw() +
  theme_classic(base_size = 15) +
 geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "Verbal Fluency F", x = "Timepoint", y = "# of words")
techs$verbal_fluency_all <- techs$verbal_fluency_s + techs$verbal_fluency_a + techs$verbal_fluency_f
techs$verbal_fluency_all_v2 <- techs$verbal_fluency_s_v2 + techs$verbal_fluency_a_v2 + techs$verbal_fluency_f_v2

long_df_vf_s <- techs %>%
  select(name, Group, verbal_fluency_s, verbal_fluency_s_v2) %>%
  gather(key = "timepoint", value = "value", verbal_fluency_s, verbal_fluency_s_v2)
long_df_vf_s <- long_df_vf_s %>%
  mutate(timepoint = ifelse(timepoint == "verbal_fluency_s", "1", "2"))
ggplot(long_df_vf_s, aes(x = timepoint, y = value, group = name, color = as.factor(Group))) +
  geom_line(linetype = "dashed") +
  theme_bw() +
  theme_classic(base_size = 15) +
 geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "Verbal Fluency S", x = "Timepoint", y = "# of words")
long_df_vf_cat <- techs %>%
  select(name, Group, verbal_fluency_animals, verbal_fluency_animals_v2) %>%
  gather(key = "timepoint", value = "value", verbal_fluency_animals, verbal_fluency_animals_v2)
long_df_vf_cat <- long_df_vf_cat %>%
  mutate(timepoint = ifelse(timepoint == "verbal_fluency_animals", "1", "2"))
ggplot(long_df_vf_cat, aes(x = timepoint, y = value, group = name, color = as.factor(Group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE, size = 1.5) +
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "Verbal Fluency Categories", x = "Timepoint", y = "# of words")
long_df_vf_all <- techs %>%
  select(name, Group, verbal_fluency_all, verbal_fluency_all_v2) %>%
  gather(key = "timepoint", value = "value", verbal_fluency_all, verbal_fluency_all_v2)
long_df_vf_all <- long_df_vf_all %>%
  mutate(timepoint = ifelse(timepoint == "verbal_fluency_all", "1", "2"))
ggplot(long_df_vf_all, aes(x = timepoint, y = value, group = name, color = as.factor(Group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
   theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE, size = 1.5) +
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "Verbal Fluency All Phonemic", x = "Timepoint", y = "# of words")
```


```{r pre/post data}
long_df_vo2 <- techs %>%
  select(name, Group, relative_vo2max_agecorrected_baseline, relative_vo2max_agecorrected_end) %>%
  gather(key = "timepoint", value = "value", relative_vo2max_agecorrected_baseline, relative_vo2max_agecorrected_end)
long_df_vo2 <- long_df_vo2 %>%
  mutate(timepoint = ifelse(timepoint == "relative_vo2max_agecorrected_baseline", "1", "2"))
ggplot(long_df_vo2, aes(x = timepoint, y = value, group = name, color = as.factor(Group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
   theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "Relative VO2max", x = "Timepoint", y = "VO2Max")

long_df_bess <- techs %>%
  select(name, Group, bess_sum_baseline, bess_sum_endpoint) %>%
  gather(key = "timepoint", value = "value", bess_sum_baseline, bess_sum_endpoint)
long_df_bess <- long_df_bess %>%
  mutate(timepoint = ifelse(timepoint == "bess_sum_baseline", "1", "2"))
ggplot(long_df_bess, aes(x = timepoint, y = value, group = name, color = as.factor(Group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
   theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "BESS", x = "Timepoint", y = "Number of Errors")
```


```{r pre/post data}
long_df_tmt_a <- techs %>%
  select(name, Group, tm_time_a, tm_time_a_v2) %>%
  gather(key = "timepoint", value = "value",  tm_time_a, tm_time_a_v2)
long_df_tmt_a <- long_df_tmt_a %>%
  mutate(timepoint = ifelse(timepoint == "tm_time_a", "1", "2"))
time_components <- strsplit(long_df_tmt_a$value, ":")
long_df_tmt_a$value <- sapply(time_components, function(x) as.numeric(x[1]) * 60 + as.numeric(x[2]))
ggplot(long_df_tmt_a, aes(x = timepoint, y = value, group = name, color = as.factor(Group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
   theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "TMT A", x = "Timepoint", y = "TMTA (seconds)")

long_df_tmt_b <- techs %>%
  select(name, Group, tm_time_b, tm_time_b_v2) %>%
  gather(key = "timepoint", value = "value",  tm_time_b, tm_time_b_v2)
long_df_tmt_b <- long_df_tmt_b %>%
  mutate(timepoint = ifelse(timepoint == "tm_time_b", "1", "2"))
time_components <- strsplit(long_df_tmt_b$value, ":")
long_df_tmt_b$value <- sapply(time_components, function(x) as.numeric(x[1]) * 60 + as.numeric(x[2]))
ggplot(long_df_tmt_b, aes(x = timepoint, y = value, group = name, color = name)) +
  geom_line() +
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_line(size = 2) + 
  labs(title = "TMT B", x = "Timepoint", y = "TMTB (seconds)")
ggplot(long_df_tmt_b, aes(x = timepoint, y = value, group = name, color = as.factor(Group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
   theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "TMT B", x = "Timepoint", y = "TMTB (seconds)")

```

```{r}
#hvlt
techs$hvlt_IR_all <- techs$t1_correct + techs$t2_correct + techs$t3_correct 
techs$hvlt_IR_all_end <- techs$t1_correct_v2 + techs$t2_correct_v2 + techs$t3_correct_v2

long_df_hvlt <- techs %>%
  select(name, Group, hvlt_IR_all, hvlt_IR_all_end) %>%
  gather(key = "timepoint", value = "value", hvlt_IR_all, hvlt_IR_all_end)
long_df_hvlt <- long_df_hvlt %>%
  mutate(timepoint = ifelse(timepoint == "hvlt_IR_all", "1", "2"))
ggplot(long_df_hvlt, aes(x = timepoint, y = value, group = name, color = as.factor(Group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
   theme_bw() +
  theme_classic(base_size = 15) +
    geom_smooth(aes(group = Group), method = "lm", se = FALSE, size = 1.5) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "HVLT IR", x = "Timepoint", y = "HVLT IR")
long_df_hvlt_delay <- techs %>%
  select(name, Group, t4_correct, t4_correct_v2) %>%
  gather(key = "timepoint", value = "value", t4_correct, t4_correct_v2)
long_df_hvlt_delay <- long_df_hvlt_delay %>%
  mutate(timepoint = ifelse(timepoint == "t4_correct", "1", "2"))
ggplot(long_df_hvlt_delay, aes(x = timepoint, y = value, group = name, color = as.factor(Group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE, size = 1.5) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale

  labs(title = "HVLT Delay", x = "Timepoint", y = "HVLT Delay")

long_df_hvlt_recognition <- techs %>%
  select(name, Group, recognition_score, recognition_score_v2) %>%
  gather(key = "timepoint", value = "value", recognition_score, recognition_score_v2)
long_df_hvlt_recognition <- long_df_hvlt_recognition %>%
  mutate(timepoint = ifelse(timepoint == "recognition_score", "1", "2"))
ggplot(long_df_hvlt_recognition, aes(x = timepoint, y = value, group = name, color = as.factor(Group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
   geom_smooth(aes(group = Group), method = "lm", se = FALSE, size = 1.5) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "HVLT Recognition", x = "Timepoint", y = "HVLT Recognition (# errors)")

```


```{r}
#histogram of sex by group
ggplot(techs, aes(x = factor(sex_factor), fill = as.factor(intervention_group))) +
  geom_histogram(stat = "count", position = "dodge") +  # Adjusting position of bars
  labs(x = "Category", y = "Count", title = "Count of Each Category for Sex") +
  scale_fill_manual(values = c("black", "red", "grey", "lightgreen"))
#histogram of age by group
ggplot(techs, aes(x = factor(age), fill = as.factor(intervention_group))) +
  geom_histogram(stat = "count", position = "dodge") +  # Adjusting position of bars
  labs(x = "Category", y = "Count", title = "Count of Each Category for Age") +
  scale_fill_manual(values = c("black", "red", "grey", "lightgreen"))
ggplot(techs, aes(x = as.factor(intervention_group), y = age, fill = as.factor(intervention_group))) +
  geom_violin() + 
  geom_point(position = position_jitterdodge(), size = 2, color = "white") +
  stat_summary(fun = mean, geom = "text", aes(label = round(..y.., digits = 2)),
               vjust = 1.5, size = 4, color = "white") +
  labs(x = "Category", y = "Age", title = "Age") +
  scale_fill_manual(values = c("black", "red", "grey", "lightgreen"))
#histogram of age by group
ggplot(techs, aes(x = factor(days_since_injury), fill = as.factor(intervention_group))) +
  geom_histogram(stat = "count", position = "dodge") +  # Adjusting position of bars
  labs(x = "Category", y = "Count", title = "Days Since Injury") +
  scale_fill_manual(values = c("black", "red", "grey", "lightgreen"))
ggplot(techs, aes(x = as.factor(intervention_group), y = days_since_injury, fill = as.factor(intervention_group))) +
  geom_violin() + 
  geom_point(position = position_jitterdodge(), size = 2, color = "white") +
  stat_summary(fun = mean, geom = "text", aes(label = round(..y.., digits = 2)),
               vjust = 1.5, size = 4, color = "white") +
  labs(x = "Category", y = "Count", title = "Days Since Injury") +
  scale_fill_manual(values = c("black", "red", "grey", "lightgreen"))

```

```{r}
#adherence plot
techs1 <- techs[-14, ]

techs <- left_join(techs, adherence, by = "name")

ggplot(techs1, aes(x = as.factor(randomization_group), y = Adherence, fill = as.factor(randomization_group))) +
  geom_boxplot() + 
  geom_point() +
  labs(x = "Category", y = "Adherence (%)", title = "Age") +
  scale_fill_manual(values = c("#FBAE2D", "#052844"))  +
  scale_x_discrete(labels = c("0" = "Aerobic", "1" = "Balance")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black"),  
        axis.ticks = element_line(color = "black")) 

#techs tbi poster graphs
ggplot(long_techs, aes(x = time_point, y = heart_rate_perc, color = factor(randomization_group))) +
    geom_line(aes(group = name), alpha = 0.5) +
    geom_smooth(method = "lm", se = FALSE, aes(group = randomization_group), size = 3) +  # Add trend lines
  scale_color_manual(values = c("#FBAE2D", "#052844"), 
                     name = "Randomization Group",
                     labels = c("0" = "Aerobic", "1" = "Balance")) +
  labs(x = "Time (Minutes)", y = "Heart Rate (% of max)", title = "HR Over Time for All Participants") +
  scale_x_discrete(labels = c("baseline_hr_perc" = "0", "min05_hr_perc" = "5", "min10_hr_perc" = "10", "min15_hr_perc" = "15", "min20_hr_perc" = "20", "min25_hr_perc" = "25", "min30_hr_perc" = "30")) +
  theme(panel.grid.major = element_blank(),    # Remove major gridlines
        panel.grid.minor = element_blank(),    # Remove minor gridlines
        panel.background = element_rect(fill = "white"),  # Set background to white
        axis.line = element_line(color = "black"),  # Specify axis line color
        axis.ticks = element_line(color = "black")) + 
    guides(color = guide_legend(title = "Randomization Group"))  # Set legend title

ggplot(long_df_hvlt_recognition, aes(x = timepoint, y = value, group = name, color = as.factor(randomization_group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 10)  +
  theme(panel.grid.major = element_blank(),    # Remove major gridlines
        panel.grid.minor = element_blank(),    # Remove minor gridlines
        panel.background = element_rect(fill = "white"),  # Set background to white
        axis.line = element_line(color = "black"),  # Specify axis line color
        axis.ticks = element_line(color = "black")) +
     geom_smooth(aes(group = randomization_group), method = "lm", se = FALSE, size = 1.5) +  # Adding best fit line by group
  scale_color_manual(values = c("#FBAE2D", "#052844"), 
                     name = "Randomization Group",
                     labels = c("0" = "Aerobic", "1" = "Balance")) + # Setting color scale
  labs(title = "HVLT Recognition", x = "Timepoint", y = "HVLT Recognition (# errors)")
ggplot(long_df_hvlt_delay, aes(x = timepoint, y = value, group = name, color = as.factor(randomization_group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 10)  +
  theme(panel.grid.major = element_blank(),    # Remove major gridlines
        panel.grid.minor = element_blank(),    # Remove minor gridlines
        panel.background = element_rect(fill = "white"),  # Set background to white
        axis.line = element_line(color = "black"),  # Specify axis line color
        axis.ticks = element_line(color = "black")) +
     geom_smooth(aes(group = randomization_group), method = "lm", se = FALSE, size = 1.5) +  # Adding best fit line by group
  scale_color_manual(values = c("#FBAE2D", "#052844"), 
                     name = "Randomization Group",
                     labels = c("0" = "Aerobic", "1" = "Balance")) + # Setting color scale
  labs(title = "HVLT Delayed Recall", x = "Timepoint", y = "HVLT Delayed Recall (# of words)")
ggplot(long_df_hvlt, aes(x = timepoint, y = value, group = name, color = as.factor(randomization_group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15)  +
  theme(panel.grid.major = element_blank(),    # Remove major gridlines
        panel.grid.minor = element_blank(),    # Remove minor gridlines
        panel.background = element_rect(fill = "white"),  # Set background to white
        axis.line = element_line(color = "black"),  # Specify axis line color
        axis.ticks = element_line(color = "black")) +
     geom_smooth(aes(group = randomization_group), method = "lm", se = FALSE, size = 1.5) +  # Adding best fit line by group
  scale_color_manual(values = c("#FBAE2D", "#052844"), 
                     name = "Randomization Group",
                     labels = c("0" = "Aerobic", "1" = "Balance")) + # Setting color scale
  labs(title = "HVLT Immediate Recall", x = "Timepoint", y = "HVLT Recall (# of words)")
ggplot(long_df_tmt_b, aes(x = timepoint, y = value, group = name, color = as.factor(randomization_group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15)  +
  theme(panel.grid.major = element_blank(),    # Remove major gridlines
        panel.grid.minor = element_blank(),    # Remove minor gridlines
        panel.background = element_rect(fill = "white"),  # Set background to white
        axis.line = element_line(color = "black"),  # Specify axis line color
        axis.ticks = element_line(color = "black")) +
  scale_x_discrete(labels = c("tm_time_b" = "Pre", "tm_time_b_v2" = "Post")) +
     geom_smooth(aes(group = randomization_group), method = "lm", se = FALSE, size = 1.5) +  # Adding best fit line by group
  scale_color_manual(values = c("#FBAE2D", "#052844"), 
                     name = "Randomization Group",
                     labels = c("0" = "Aerobic", "1" = "Balance")) + # Setting color scale
  labs(title = "Trail Making Test B", x = "Timepoint", y = "Time (seconds)")

ggplot(long_df_tmt_a, aes(x = timepoint, y = value, group = name, color = as.factor(randomization_group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 10)  +
  theme(panel.grid.major = element_blank(),    # Remove major gridlines
        panel.grid.minor = element_blank(),    # Remove minor gridlines
        panel.background = element_rect(fill = "white"),  # Set background to white
        axis.line = element_line(color = "black"),  # Specify axis line color
        axis.ticks = element_line(color = "black")) +
  scale_x_discrete(labels = c("tm_time_a" = "Pre", "tm_time_a_v2" = "Post")) +
     geom_smooth(aes(group = randomization_group), method = "lm", se = FALSE, size = 1.5) +  # Adding best fit line by group
  scale_color_manual(values = c("#FBAE2D", "#052844"), 
                     name = "Randomization Group",
                     labels = c("0" = "Aerobic", "1" = "Balance")) + # Setting color scale
  labs(title = "Trail Making Test A", x = "Timepoint", y = "Time (seconds)")

ggplot(long_df_vo2, aes(x = timepoint, y = value, group = name, color = as.factor(randomization_group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15)  +
  theme(panel.grid.major = element_blank(),    # Remove major gridlines
        panel.grid.minor = element_blank(),    # Remove minor gridlines
        panel.background = element_rect(fill = "white"),  # Set background to white
        axis.line = element_line(color = "black"),  # Specify axis line color
        axis.ticks = element_line(color = "black")) +
  scale_x_discrete(labels = c("1" = "Pre", "2" = "Post")) +
     geom_smooth(aes(group = randomization_group), method = "lm", se = FALSE, size = 1.5) +  # Adding best fit line by group
  scale_color_manual(values = c("#FBAE2D", "#052844"), 
                     name = "Randomization Group",
                     labels = c("0" = "Aerobic", "1" = "Balance")) + # Setting color scale
  labs(title = "Relative VO2 Max", x = "Timepoint", y = "Relative VO2 Max (mL/kg/min)")

ggplot(long_df_bess, aes(x = timepoint, y = value, group = name, color = as.factor(randomization_group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15)  +
  theme(panel.grid.major = element_blank(),    # Remove major gridlines
        panel.grid.minor = element_blank(),    # Remove minor gridlines
        panel.background = element_rect(fill = "white"),  # Set background to white
        axis.line = element_line(color = "black"),  # Specify axis line color
        axis.ticks = element_line(color = "black")) +
  scale_x_discrete(labels = c("1" = "Pre", "2" = "Post")) +
     geom_smooth(aes(group = randomization_group), method = "lm", se = FALSE, size = 1.5) +  # Adding best fit line by group
  scale_color_manual(values = c("#FBAE2D", "#052844"), 
                     name = "Randomization Group",
                     labels = c("0" = "Aerobic", "1" = "Balance")) + # Setting color scale
  labs(title = "Balance", x = "Timepoint", y = "BESS (# of Errors)")


ggplot(long_df_vf_all, aes(x = timepoint, y = value, group = name, color = as.factor(randomization_group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 10)  +
  theme(panel.grid.major = element_blank(),    # Remove major gridlines
        panel.grid.minor = element_blank(),    # Remove minor gridlines
        panel.background = element_rect(fill = "white"),  # Set background to white
        axis.line = element_line(color = "black"),  # Specify axis line color
        axis.ticks = element_line(color = "black")) +
  scale_x_discrete(labels = c("1" = "Pre", "2" = "Post")) +
     geom_smooth(aes(group = randomization_group), method = "lm", se = FALSE, size = 1.5) +  # Adding best fit line by group
  scale_color_manual(values = c("#FBAE2D", "#052844"), 
                     name = "Randomization Group",
                     labels = c("0" = "Aerobic", "1" = "Balance")) + # Setting color scale
  labs(title = "Verbal Fluency", x = "Timepoint", y = "VF All (# of Words)")

ggplot(long_df_vf_cat, aes(x = timepoint, y = value, group = name, color = as.factor(randomization_group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 20)  +
  theme(panel.grid.major = element_blank(),    # Remove major gridlines
        panel.grid.minor = element_blank(),    # Remove minor gridlines
        panel.background = element_rect(fill = "white"),  # Set background to white
        axis.line = element_line(color = "black"),  # Specify axis line color
        axis.ticks = element_line(color = "black")) +
  scale_x_discrete(labels = c("1" = "Pre", "2" = "Post")) +
     geom_smooth(aes(group = randomization_group), method = "lm", se = FALSE, size = 1.5) +  # Adding best fit line by group
  scale_color_manual(values = c("#FBAE2D", "#052844"), 
                     name = "Randomization Group",
                     labels = c("0" = "Aerobic", "1" = "Balance")) + # Setting color scale
  labs(title = "Verbal Fluency (Category)", x = "Timepoint", y = "VF Category (# of Words)")


mean(subset(techs1, randomization_group == 1)$Adherence)
mean(subset(techs1, randomization_group == 0)$Adherence)
mean(techs1$Adherence)
```


```{r}
datetime_string <- "1899-12-31 00:43:00 UTC"

# Convert the datetime string to POSIXct
datetime_posix <- as.POSIXct(datetime_string, tz = "UTC", format = "%Y-%m-%d %H:%M:%S")

# Convert to numerical seconds since Unix epoch
seconds_since_epoch <- as.numeric(datetime_posix)

# Print the result
print(seconds_since_epoch)
```

```{r}
#prepost correlations

t.test(techs$verbal_fluency_all, techs$verbal_fluency_all_v2)
cor.test(techs$verbal_fluency_all, techs$verbal_fluency_all_v2)

t.test(techs$verbal_fluency_animals, techs$verbal_fluency_animals_v2)
cor.test(techs$verbal_fluency_animals, techs$verbal_fluency_animals_v2)

t.test(techs$tm_time_a, techs$tm_time_a_v2)
cor.test(techs$tm_time_a, techs$tm_time_a_v2)

t.test(techs$tm_time_b, techs$tm_time_b_v2)
cor.test(techs$tm_time_b, techs$tm_time_b_v2)

t.test(techs$hvlt_IR_all, techs$hvlt_IR_all_end)
cor.test(techs$hvlt_IR_all, techs$hvlt_IR_all_end)

t.test(techs$t4_correct, techs$t4_correct_v2)
cor.test(techs$t4_correct, techs$t4_correct_v2)

t.test(techs$global_v1, techs$global_v2)
cor.test(techs$global_v1, techs$global_v2)

t.test(techs$bess_sum_baseline, techs$bess_sum_endpoint)
cor.test(techs$bess_sum_baseline, techs$bess_sum_endpoint)
```


```{r}

long_df_FA <- dti %>%
  select(name, randomization_group, mean_fa, mean_fa_t2) %>%
  gather(key = "timepoint", value = "value", mean_fa, mean_fa_t2)
long_df_FA <- long_df_FA %>%
  mutate(timepoint = ifelse(timepoint == "mean_fa", "1", "2"))

ggplot(long_df_FA, aes(x = timepoint, y = value, group = name, color = as.factor(randomization_group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
 geom_smooth(aes(group = randomization_group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "FA", x = "Timepoint", y = "FA")
  
  
  
long_df_AD <- dti %>%
  select(name, randomization_group, mean_ad, mean_ad_t2) %>%
  gather(key = "timepoint", value = "value", mean_ad, mean_ad_t2)
long_df_AD <- long_df_AD %>%
  mutate(timepoint = ifelse(timepoint == "mean_ad", "1", "2"))

ggplot(long_df_AD, aes(x = timepoint, y = value, group = name, color = as.factor(randomization_group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
 geom_smooth(aes(group = randomization_group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "AD", x = "Timepoint", y = "AD")
  
  
long_df_MD <- dti %>%
  select(name, randomization_group, mean_md, mean_md_t2) %>%
  gather(key = "timepoint", value = "value", mean_md, mean_md_t2)
long_df_MD <- long_df_MD %>%
  mutate(timepoint = ifelse(timepoint == "mean_md", "1", "2"))

ggplot(long_df_MD, aes(x = timepoint, y = value, group = name, color = as.factor(randomization_group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
 geom_smooth(aes(group = randomization_group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "MD", x = "Timepoint", y = "MD")
  
  
long_df_RD <- dti %>%
  select(name, randomization_group, mean_rd, mean_rd_t2) %>%
  gather(key = "timepoint", value = "value", mean_rd, mean_rd_t2)
long_df_RD <- long_df_RD %>%
  mutate(timepoint = ifelse(timepoint == "mean_rd", "1", "2"))

ggplot(long_df_RD, aes(x = timepoint, y = value, group = name, color = as.factor(randomization_group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
 geom_smooth(aes(group = randomization_group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "RD", x = "Timepoint", y = "RD")
  
ggplot(df_clean, aes(x = as.factor(randomization_group), y = ad_change, fill = as.factor(randomization_group))) +
  geom_violin() + 
  geom_point(position = position_jitterdodge(), size = 2, color = "white") +
  labs(x = "Category", y = "AD", title = "Change in AD") +
  scale_fill_manual(values = c("black", "red"))

ggplot(df_clean, aes(x = as.factor(randomization_group), y = fa_change, fill = as.factor(randomization_group))) +
  geom_violin() + 
  geom_point(position = position_jitterdodge(), size = 2, color = "white") +
  labs(x = "Category", y = "FA", title = "Change in FA") +
  scale_fill_manual(values = c("black", "red"))
  
ggplot(df_clean, aes(x = as.factor(randomization_group), y = rd_change, fill = as.factor(randomization_group))) +
  geom_violin() + 
  geom_point(position = position_jitterdodge(), size = 2, color = "white") +
  labs(x = "Category", y = "RD", title = "Change in RD") +
  scale_fill_manual(values = c("black", "red"))
  
  ggplot(df_clean, aes(x = as.factor(randomization_group), y = md_change, fill = as.factor(randomization_group))) +
  geom_violin() + 
  geom_point(position = position_jitterdodge(), size = 2, color = "white") +
  labs(x = "Category", y = "MD", title = "Change in MD") +
  scale_fill_manual(values = c("black", "red"))
  
ggplot(df_clean, aes(x = ad_change, y = tm_time_b_change, color = as.factor(randomization_group))) +
  geom_point() +  # Add points for the correlation
  geom_smooth(method = "lm", se = FALSE) +  # Add the best fit line
  theme_bw() +
  theme_classic(base_size = 15) +
  scale_color_manual(values = c("black", "red")) +  # Set color scale
  labs(title = "Correlation between AD Change and TM Time B Change", 
       x = "AD Change", 
       y = "TM Time B Change")
```
#adding graphs with the "ids"
```{r}
ggplot(long_df_FA, aes(x = timepoint, y = value, group = name, color = as.factor(randomization_group_factor))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 10)  +
  theme(panel.grid.major = element_blank(),    # Remove major gridlines
        panel.grid.minor = element_blank(),    # Remove minor gridlines
        panel.background = element_rect(fill = "white"),  # Set background to white
        axis.line = element_line(color = "black"),  # Specify axis line color
        axis.ticks = element_line(color = "black")) +
  scale_x_discrete(labels = c("1" = "Pre", "2" = "Post")) +
  geom_smooth(aes(group = randomization_group_factor), method = "lm", se = FALSE, size = 1.5) +  # Adding best fit line by group
  scale_color_manual(values = c("#FBAE2D", "#052844"), 
                     name = "Randomization Group",
                     labels = c("0" = "Aerobic", "1" = "Balance")) +  # Setting color scale
  labs(title = "Verbal Fluency", x = "Timepoint", y = "VF All (# of Words)") +
  geom_text(aes(label = name), hjust = 0, vjust = -0.5, size = 3)  # Add text labels for 'name'


```

#removing 4 and 8
```{r}
techs_filtered <- techs %>% filter(!name %in% c(4, 8))
balance_ids <- c("1", "7", "8", "9", "17", "21", "22", "24", "29")
aerobic_ids <- c("3", "4", "10", "11", "12", "15", "19", "25", "26", "27")
Ivy <- c("2")
Pooja <- c("28")
techs_filtered <- techs_filtered %>%
  mutate(
    Group = case_when(
      name %in% balance_ids ~ "balance",
      name %in% aerobic_ids ~ "aerobic",
      name %in% Ivy ~ "Ivy",
      name %in% Pooja ~ "Pooja",
      TRUE ~ NA_character_  # Assign NA to names not in any list
    )
  )

# Transform data into long format
long_df_vf_a <- techs_filtered %>%
  select(name, Group, verbal_fluency_a, verbal_fluency_a_v2) %>%
  gather(key = "timepoint", value = "value", verbal_fluency_a, verbal_fluency_a_v2)

# Update timepoint labels
long_df_vf_a <- long_df_vf_a %>%
  mutate(timepoint = ifelse(timepoint == "verbal_fluency_a", "1", "2"))
#plot
ggplot(long_df_vf_a %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "Verbal Fluency A", x = "Timepoint", y = "# of words")

# Transform data into long format VF S
long_df_vf_s <- techs_filtered %>%
  select(name, Group, verbal_fluency_s, verbal_fluency_s_v2) %>%
  gather(key = "timepoint", value = "value", verbal_fluency_s, verbal_fluency_s_v2)

# Update timepoint labels
long_df_vf_s <- long_df_vf_s %>%
  mutate(timepoint = ifelse(timepoint == "verbal_fluency_s", "1", "2"))
#plot
ggplot(long_df_vf_s %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "Verbal Fluency S", x = "Timepoint", y = "# of words") 

# Transform data into long format VF F
long_df_vf_f <- techs_filtered %>%
  select(name, Group, verbal_fluency_f, verbal_fluency_f_v2) %>%
  gather(key = "timepoint", value = "value", verbal_fluency_f, verbal_fluency_f_v2)

# Update timepoint labels
long_df_vf_f <- long_df_vf_f %>%
  mutate(timepoint = ifelse(timepoint == "verbal_fluency_f", "1", "2"))
#plot
ggplot(long_df_vf_f %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "Verbal Fluency F", x = "Timepoint", y = "# of words") 

# Transform data into long format VF Phonemic
long_df_vf_all <- techs_filtered %>%
  select(name, Group, verbal_fluency_all, verbal_fluency_all_v2) %>%
  gather(key = "timepoint", value = "value", verbal_fluency_all, verbal_fluency_all_v2)
# Update timepoint labels
long_df_vf_all <- long_df_vf_all %>%
  mutate(timepoint = ifelse(timepoint == "verbal_fluency_all", "1", "2"))
#plot
ggplot(long_df_vf_all %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "Verbal Fluency Phonemic", x = "Timepoint", y = "# of words") 
# Transform data into long format VF cat
long_df_vf_cat <- techs_filtered %>%
  select(name, Group, verbal_fluency_animals, verbal_fluency_animals_v2) %>%
  gather(key = "timepoint", value = "value", verbal_fluency_animals, verbal_fluency_animals_v2)
# Update timepoint labels
long_df_vf_cat <- long_df_vf_cat %>%
  mutate(timepoint = ifelse(timepoint == "verbal_fluency_animals", "1", "2"))
#plot
ggplot(long_df_vf_cat %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "Verbal Fluency Categories", x = "Timepoint", y = "# of words") 

# Transform data into long format TMT A
long_df_vf_tmta <- techs_filtered %>%
  select(name, Group, tm_time_a, tm_time_a_v2) %>%
  gather(key = "timepoint", value = "value", tm_time_a, tm_time_a_v2)
# Update timepoint labels
long_df_vf_tmta <- long_df_vf_tmta %>%
  mutate(timepoint = ifelse(timepoint == "tm_time_a", "1", "2"))
#plot
ggplot(long_df_vf_tmta %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "TMT A", x = "Timepoint", y = "Seconds") 

# Transform data into long format TMT B
long_df_vf_tmtb <- techs_filtered %>%
  select(name, Group, tm_time_b, tm_time_b_v2) %>%
  gather(key = "timepoint", value = "value", tm_time_b, tm_time_b_v2)
# Update timepoint labels
long_df_vf_tmtb <- long_df_vf_tmtb %>%
  mutate(timepoint = ifelse(timepoint == "tm_time_b", "1", "2"))
#plot
ggplot(long_df_vf_tmtb %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "TMT B", x = "Timepoint", y = "Seconds") 

# Transform data into long format HVLT IR
long_df_hvlt_ir <- techs_filtered %>%
  select(name, Group, hvlt_IR_all, hvlt_IR_all_end) %>%
  gather(key = "timepoint", value = "value", hvlt_IR_all, hvlt_IR_all_end)
# Update timepoint labels
long_df_hvlt_ir <- long_df_hvlt_ir %>%
  mutate(timepoint = ifelse(timepoint == "hvlt_IR_all", "1", "2"))
#plot
ggplot(long_df_hvlt_ir %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "HVLT Immediate Recall", x = "Timepoint", y = "# of Words") 
#delay recall
long_df_hvlt_dr <- techs_filtered %>%
  select(name, Group, t4_correct, t4_correct_v2) %>%
  gather(key = "timepoint", value = "value", t4_correct, t4_correct_v2)
# Update timepoint labels
long_df_hvlt_dr <- long_df_hvlt_dr %>%
  mutate(timepoint = ifelse(timepoint == "t4_correct", "1", "2"))
#plot
ggplot(long_df_hvlt_dr %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "HVLT Delay Recall", x = "Timepoint", y = "# of Words")

#Errors
long_df_hvlt_recognition <- techs_filtered %>%
  select(name, Group, recognition_score, recognition_score_v2) %>%
  gather(key = "timepoint", value = "value", recognition_score, recognition_score_v2)
# Update timepoint labels
long_df_hvlt_recognition <- long_df_hvlt_recognition %>%
  mutate(timepoint = ifelse(timepoint == "recognition_score", "1", "2"))
#plot
ggplot(long_df_hvlt_recognition %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "HVLT Recognition", x = "Timepoint", y = "# of Errors")

#VO2
long_df_vo2 <- techs_filtered %>%
  select(name, Group, relative_vo2max_agecorrected_baseline, relative_vo2max_agecorrected_end) %>%
  gather(key = "timepoint", value = "value", relative_vo2max_agecorrected_baseline, relative_vo2max_agecorrected_end)
# Update timepoint labels
long_df_vo2 <- long_df_vo2 %>%
  mutate(timepoint = ifelse(timepoint == "relative_vo2max_agecorrected_baseline", "1", "2"))
#plot
ggplot(long_df_vo2 %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "Relative VO2", x = "Timepoint", y = "VO2max")

#BESS
long_df_bess <- techs_filtered %>%
  select(name, Group, bess_sum_baseline, bess_sum_endpoint) %>%
  gather(key = "timepoint", value = "value", bess_sum_baseline, bess_sum_endpoint)
# Update timepoint labels
long_df_bess <- long_df_bess %>%
  mutate(timepoint = ifelse(timepoint == "bess_sum_baseline", "1", "2"))
#plot
ggplot(long_df_bess %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "BESS", x = "Timepoint", y = "# of errors")
```

#psqi filtered
```{r}
psqi_filtered <- techs_psqi %>% filter(!name %in% c(4, 8))
psqi_filtered <- psqi_filtered %>%
  mutate(
    Group = case_when(
      name %in% balance_ids ~ "balance",
      name %in% aerobic_ids ~ "aerobic",
      name %in% Ivy ~ "Ivy",
      name %in% Pooja ~ "Pooja",
      TRUE ~ NA_character_  # Assign NA to names not in any list
    )
  )
long_df_psqi <- psqi_filtered %>%
  select(name, Group, totalpsqi, totalpsqi_endpoint) %>%
  gather(key = "timepoint", value = "value", totalpsqi, totalpsqi_endpoint)
# Update timepoint labels
long_df_psqi <- long_df_psqi %>%
  mutate(timepoint = ifelse(timepoint == "totalpsqi", "1", "2"))
#plot
ggplot(long_df_psqi %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "blue")) +  # Setting color scale
  labs(title = "PSQI", x = "Timepoint", y = "Score")
```

#PROMIS filtered
```{r}
promis_filtered <- promis %>% filter(!name %in% c(4, 8))
promis_filtered <- promis_filtered %>%
  mutate(
    Group = case_when(
      name %in% balance_ids ~ "balance",
      name %in% aerobic_ids ~ "aerobic",
      name %in% Ivy ~ "Ivy",
      name %in% Pooja ~ "Pooja",
      TRUE ~ NA_character_  # Assign NA to names not in any list
    )
  )
#cog func
long_df_cogfun <- promis_filtered %>%
  select(name, Group, cog_func_t, cog_func_t_v2) %>%
  gather(key = "timepoint", value = "value", cog_func_t, cog_func_t_v2)
# Update timepoint labels
long_df_cogfun <- long_df_cogfun %>%
  mutate(timepoint = ifelse(timepoint == "cog_func_t", "1", "2"))
#plot
ggplot(long_df_cogfun %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "Promis Cog Function", x = "Timepoint", y = "T Score")

#mental
long_df_mental <- promis_filtered %>%
  select(name, Group, gmh_t, gmh_t_v2) %>%
  gather(key = "timepoint", value = "value", gmh_t, gmh_t_v2)
# Update timepoint labels
long_df_mental <- long_df_mental %>%
  mutate(timepoint = ifelse(timepoint == "gmh_t", "1", "2"))
#plot
ggplot(long_df_mental %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "Promis Mental Health", x = "Timepoint", y = "T Score")

#Physical
long_df_physical <- promis_filtered %>%
  select(name, Group, gph_t, gph_t_v2) %>%
  gather(key = "timepoint", value = "value", gph_t, gph_t_v2)
# Update timepoint labels
long_df_physical <- long_df_physical %>%
  mutate(timepoint = ifelse(timepoint == "gph_t", "1", "2"))
#plot
ggplot(long_df_physical %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "Promis Physical Health", x = "Timepoint", y = "T Score")

#Global
long_df_global <- promis_filtered %>%
  select(name, Group, global_v1, global_v2) %>%
  gather(key = "timepoint", value = "value", global_v1, global_v2)
# Update timepoint labels
long_df_global <- long_df_global %>%
  mutate(timepoint = ifelse(timepoint == "global_v1", "1", "2"))
#plot
ggplot(long_df_global %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = Group)) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red", "orange", "blue")) +  # Setting color scale
  labs(title = "Promis Global Health", x = "Timepoint", y = "T Score")
```

