---
title: "PSQI"
output: html_document
---


```{r}
#analyzing PSQI scores 
#old
techs$time_to_sleep_baseline <- as.numeric(techs$time_to_sleep_baseline)
techs$PSQ2score <- cut(techs$time_to_sleep_baseline, breaks=c(-Inf, 16, 31, 60, Inf), labels=c("1","2","3","4"))
techs$PSQ4score <- cut(techs$PSQ4A, breaks=c(-Inf, 5, 6, 7, Inf), labels=c("4","3","2", "1"))
techs$PSQ2score<-replace(techs$PSQ2, techs$PSQ2>30, 1)
techs$PSQ2score <- cut(techs$PSQ2, 
                      breaks=c(-Inf, 16, 31, 60, Inf), 
                      labels=c("1","2","3", "4"))
info$PSQ_comp7 <- rowMeans(info[ , c("PSQ8","PSQ9")], na.rm=TRUE)

info$PSQ5score <- rowSums(info[ , c(info$PSQ5B,info$PSQ5J)], na.rm=TRUE)
info$PSQ5score <- cbind(info$PSQ5B,info$PSQ5C,info$PSQ5D,info$PSQ5E,info$PSQ5F,info$PSQ5G,info$PSQ5H,info$PSQ5I,info$PSQ5J)
info$PSQ_comp2 <- info$PSQ5A + info$PSQ2score
info$PSQ_comp2 <- info$PSQ_comp2/2
info$PSQ_comp6 <- info$PSQ6
info$PSQ_comp5 <- info$PSQ5B + info$PSQ5C + info$PSQ5D + info$PSQ5E + info$PSQ5F + info$PSQ5H + info$PSQ5I + info$PSQ5J
info$PSQ_comp5 <- cut(info$PSQ_comp5, 
                      breaks=c(-Inf, 1, 9, 19, Inf), 
                      labels=c("1","2","3","4"))
info$PSQ1s <- (12-info$PSQ1A)
info$PSQ1s<-replace(info$PSQ1s, info$PSQ1s>8, -4)
info$PSQ1s<-replace(info$PSQ1s, info$PSQ1s>9, -3)
info$PSQ1s<-replace(info$PSQ1s, info$PSQ1s>10, -2)
info$PSQ1s<-replace(info$PSQ1s, info$PSQ1s>13, -1)
info$PSQ_comp4 <- info$PSQ4A/info$PSQ1ib
info$PSQ_comp4 <- cut(info$PSQ_comp4, 
                      breaks=c(-Inf, .65, .74, .85, Inf), 
                      labels=c("4","3","2","1"))
info$PSQtotal <- info$PSQ_comp1 + info$PSQ_comp2 + info$PSQ_comp3 + info$PSQ_comp4 + info$PSQ_comp5 + info$PSQ_comp6 + info$PSQ_comp7

```

```{r TECHS}
#use this one
techs$comp1 <- techs$sleep_quality
techs$q2 <- cut(techs$time_to_sleep_baseline, 
                      breaks=c(-Inf, 16, 31, 60, Inf), 
                   labels=c("0","1","2", "3"))
techs$q2 <- as.numeric(techs$q2)
techs$comp2 <- rowSums(techs[ , c("q2","cantsleep")], na.rm=TRUE)
techs$comp2 <- cut(techs$comp2, 
                      breaks=c(-Inf, 1, 3, 4, Inf), 
                   labels=c("0","1","2", "3"))
techs$sleep_baseline <- as.numeric(techs$sleep_baseline)
techs$comp3 <- cut(techs$sleep_baseline, 
                       breaks=c(-Inf, 5, 6, 7, Inf), 
                       labels=c("3","2","1", "0"))
#make sure waketime and bedtime are in 24 hour format
# Convert time objects to numeric hours
convert_to_numeric_hours <- function(time_str) {
  time_str <- as.character(time_str)  # Ensure the input is a character string
  time_parts <- strsplit(time_str, ":")[[1]]  # Split the string by ":"
  hours <- as.numeric(time_parts[1])
  minutes <- as.numeric(time_parts[2]) / 60
  seconds <- as.numeric(time_parts[3]) / 3600
  return(hours + minutes + seconds)
}

# Apply the conversion and compute actual sleep
techs$actual_sleep <- sapply(1:length(techs$bedtime_baseline), function(i) {
  bed_time <- convert_to_numeric_hours(techs$bedtime_baseline[i])
  wake_time <- convert_to_numeric_hours(techs$waketime_baseline[i])

  if (is.na(bed_time) | is.na(wake_time)) {
    return(NA)  # Handle missing times
  }

  # Adjust for crossing midnight
  if (bed_time > wake_time) {
    sleep_time <- (24 - bed_time) + wake_time
  } else {
    sleep_time <- wake_time - bed_time
  }

  return(sleep_time)
})


techs$comp4 <- (techs$sleep_baseline/techs$actual_sleep)*100
techs$comp4 <- cut(techs$comp4, 
                       breaks=c(-Inf, 65, 74, 84, Inf), 
                       labels=c("3","2","1","0"))
techs$comp5 <- rowSums(techs[ , c("wakeup","bathroom", "breath","snore","cold","hot","nightmares","pain")], na.rm=TRUE)
techs$comp5 <- cut(techs$comp5, 
                      breaks=c(-Inf, 1, 9, 19, Inf), 
                      labels=c("0","1","2","3"))
techs$comp6 <- techs$meds
techs$comp7 <- rowMeans(techs[ , c("enthusiasm","trouble_staying_awake")], na.rm=TRUE)
techs$comp1 <- as.numeric(techs$comp1) 
techs$comp2 <- as.numeric(techs$comp2)
techs$comp3 <- as.numeric(techs$comp3)
techs$comp4 <- as.numeric(techs$comp4)
techs$comp5 <- as.numeric(techs$comp5)
techs$comp6 <- as.numeric(techs$comp6)
techs$comp7 <- as.numeric(techs$comp7)
techs$totalpsqi <- rowSums(techs[ , c("comp1","comp2","comp3","comp4","comp5","comp6","comp7")], na.rm=TRUE)
hist(techs$totalpsqi)
ggplot(techs, aes(x = factor(totalpsqi), fill = as.factor(intervention_group))) +
  geom_histogram(stat = "count") +
  labs(x = "Category", y = "Count", title = "Count of Each Category for PSQI") +
  scale_fill_manual(values = c("black", "red", "grey", "lightgreen"))

ggplot(techs, aes(x = as.factor(intervention_group), y = totalpsqi, fill = as.factor(intervention_group))) +
  geom_violin() + 
  geom_point(position = position_jitterdodge(), size = 2, color = "white") +
  stat_summary(fun = mean, geom = "text", aes(label = round(..y.., digits = 2)),
               vjust = 1.5, size = 4, color = "white") +
  labs(x = "Category", y = "Count", title = "Count of Each Category for PSQI") +
  scale_fill_manual(values = c("black", "red", "grey", "lightgreen"))


ggplot(techs, aes(x = as.factor(intervention_group), y = totalpsqi, fill = as.factor(intervention_group))) +
  geom_bar(stat = "summary", fun = "mean") +
  stat_summary(fun = mean, geom = "text", aes(label = round(..y.., digits = 2)),
               vjust = 1.5, size = 4, color = "white") +  # Adjusted position of text
  labs(x = "Group", y = "PSQI", title = "Mean for each group PSQI") +
  scale_fill_manual(values = c("black", "red", "grey", "lightgreen"))

```
#endpoint
```{r}
techs_psqi <- techs[!is.na(techs$sleep_quality_endpoint), ]

techs_psqi$comp1_endpoint <- techs_psqi$sleep_quality_endpoint
techs_psqi$q2_endpoint <- cut(techs_psqi$time_to_sleep_baseline_endpoint, 
                      breaks=c(-Inf, 16, 31, 60, Inf), 
                   labels=c("0","1","2", "3"))
techs_psqi$q2_endpoint <- as.numeric(techs_psqi$q2_endpoint)
techs_psqi$comp2_endpoint <- rowSums(techs_psqi[ , c("q2","cantsleep_endpoint")], na.rm=TRUE)
techs_psqi$comp2_endpoint <- cut(techs_psqi$comp2_endpoint, 
                      breaks=c(-Inf, 1, 3, 4, Inf), 
                   labels=c("0","1","2", "3"))
techs_psqi$sleep_baseline_endpoint <- as.numeric(techs_psqi$sleep_baseline_endpoint)
techs_psqi$comp3_endpoint <- cut(techs_psqi$sleep_baseline_endpoint, 
                       breaks=c(-Inf, 5, 6, 7, Inf), 
                       labels=c("3","2","1", "0"))



techs_psqi$comp4_endpoint <- (techs_psqi$sleep_baseline_endpoint/techs_psqi$actual_sleep_endpoint)*100
techs_psqi$comp4_endpoint <- cut(techs_psqi$comp4_endpoint, 
                       breaks=c(-Inf, 65, 74, 84, Inf), 
                       labels=c("3","2","1","0"))
techs_psqi$comp5_endpoint <- rowSums(techs_psqi[ , c("wakeup_endpoint","bathroom_endpoint", "breath_endpoint","snore_endpoint","cold_endpoint","hot_endpoint","nightmares_endpoint","pain_endpoint")], na.rm=TRUE)
techs_psqi$comp5_endpoint <- cut(techs_psqi$comp5_endpoint, 
                      breaks=c(-Inf, 1, 9, 19, Inf), 
                      labels=c("0","1","2","3"))
techs_psqi$comp6_endpoint <- techs_psqi$meds_endpoint
techs_psqi$comp7_endpoint <- rowMeans(techs_psqi[ , c("enthusiasm_endpoint","trouble_staying_awake_endpoint")], na.rm=TRUE)
techs_psqi$comp1_endpoint <- as.numeric(techs_psqi$comp1_endpoint) 
techs_psqi$comp2_endpoint <- as.numeric(techs_psqi$comp2_endpoint)
techs_psqi$comp3_endpoint <- as.numeric(techs_psqi$comp3_endpoint)
techs_psqi$comp4_endpoint <- as.numeric(techs_psqi$comp4_endpoint)
techs_psqi$comp5_endpoint <- as.numeric(techs_psqi$comp5_endpoint)
techs_psqi$comp6_endpoint <- as.numeric(techs_psqi$comp6_endpoint)
techs_psqi$comp7_endpoint <- as.numeric(techs_psqi$comp7_endpoint)
techs_psqi$totalpsqi_endpoint <- rowSums(techs_psqi[ , c("comp1_endpoint","comp2_endpoint","comp3_endpoint","comp4_endpoint","comp5_endpoint","comp6_endpoint","comp7_endpoint")], na.rm=TRUE)
hist(techs_psqi$totalpsqi_endpoint)
ggplot(techs_psqi, aes(x = factor(totalpsqi_endpoint), fill = as.factor(intervention_group))) +
  geom_histogram(stat = "count") +
  labs(x = "Category", y = "Count", title = "Count of Each Category for PSQI") +
  scale_fill_manual(values = c("black", "red", "grey", "lightgreen"))

ggplot(techs_psqi, aes(x = as.factor(intervention_group), y = totalpsqi_endpoint, fill = as.factor(intervention_group))) +
  geom_violin() + 
  geom_point(position = position_jitterdodge(), size = 2, color = "white") +
  stat_summary(fun = mean, geom = "text", aes(label = round(..y.., digits = 2)),
               vjust = 1.5, size = 4, color = "white") +
  labs(x = "Category", y = "Count", title = "Count of Each Category for PSQI at endpoint") +
  scale_fill_manual(values = c("black", "red", "grey", "lightgreen"))

long_df_psqi<- techs_psqi %>%
  select(name, Group, totalpsqi, totalpsqi_endpoint) %>%
  gather(key = "timepoint", value = "value", totalpsqi, totalpsqi_endpoint)
long_df_psqi <- long_df_psqi %>%
  mutate(timepoint = ifelse(timepoint == "totalpsqi", "1", "2"))

ggplot(long_df_psqi %>% filter(!is.na(Group)), aes(x = timepoint, y = value, group = name, color = as.factor(Group))) +
  geom_line(linetype = "dashed") +  # Set individual lines as dashed
  theme_bw() +
  theme_classic(base_size = 15) +
  geom_smooth(aes(group = Group), method = "lm", se = FALSE) +  # Adding best fit line by group
  scale_color_manual(values = c("black", "red")) +  # Setting color scale
  labs(title = "PSQI", x = "Timepoint", y = "PSQI")
```
