---
title: "RadarPlot"
output: html_document
date: '2024-05-17'
---

```{r setup, include=FALSE}
install.packages("fmsb")
library(fmsb)

```

## R Markdown



```{r}
techs28 <- data.frame(
    Cognition = c(37, 31),
    Brain = c(10, 10),
    Symptoms = c(0, 0),
    Fitness = c(33.187, 37.0909),
    Balance = c(6, 3)
)
techs29 <- data.frame(
    Cognition = c(60, 55),
    Brain = c(8, 9),
    Symptoms = c(0, 0),
    Fitness = c(38.66, 43.156),
    Balance = c(9, 3)
)
row.names(techs28) <- c("Baseline", "Endpoint")
techs28

max_min <- data.frame(
    Cognition = c(60, 0),
    Brain = c(11, 0),
    Symptoms = c(30, 0),
    Fitness = c(44, 0),
    Balance = c(10, 0)
)
techs28_plot <- rbind(max_min,techs28)

radarchart(
    techs28_plot, axistype = 1,
    # Customizing the plot appearance
    pcol = c("#00AFBB", "#E7B800"),    # Colors for the lines
    pfcol = c(rgb(0.2,0.5,0.5,0.5), rgb(0.8,0.2,0.5,0.5)), # Colors for the filled areas
    plwd = 2,                   # Line width
    plty = 1,                   # Line type
    cglcol = "grey",            # Color of the grid lines
    cglty = 1,                  # Type of the grid lines
    axislabcol = "grey",        # Color of the axis labels
    caxislabels = seq(0, 20, 5),# Axis labels
    vlcex = 0.8                 # Font size for the variable labels
)
```
